# JEKYLL CONFIGURATION
## custom variables
### meta
lang: kr

## system variables
# https://jekyllrb.com/docs/configuration/options/#global-configuration
# 왜캐 문서가 복잡한지... 찾기도 힘듬
timezone: Asia/Seoul

collections:
  posts:
    permalink: /:categories/:title

# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "XIYO"

#markdown: kramdown
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
#highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
#  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
#  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
#    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


## defaults configuration
# Where things are
# source              : .
# destination         : ./_site
# collections_dir     : .
# plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
# layouts_dir         : _layouts
# data_dir            : _data
# includes_dir        : _includes
# sass:
#   sass_dir: _sass
# collections:
#   posts:
#     output          : true

# Handling Reading
# safe                : false
# include             : [".htaccess"]
# exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
# keep_files          : [".git", ".svn"]
# encoding            : "utf-8"
# markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
# strict_front_matter : false

# Filtering Content
# show_drafts         : null
# limit_posts         : 0
# future              : false
# unpublished         : false

# Plugins
# whitelist           : []
# plugins             : []

# Conversion
# markdown            : kramdown
# highlighter         : rouge
# lsi                 : false
# excerpt_separator   : "\n\n"
# incremental         : false

# Serving
# detach              : false
# port                : 4000
# host                : 127.0.0.1
# baseurl             : "" # does not include hostname
# show_dir_listing    : false

# Outputting
# permalink           : date
# paginate_path       : /page:num
# timezone            : null

# quiet               : false
# verbose             : false
# defaults            : []

# liquid:
#   error_mode        : warn
#   strict_filters    : false
#   strict_variables  : false

# Markdown Processors
# kramdown:
#   auto_ids          : true
#   entity_output     : as_char
#   toc_levels        : [1, 2, 3, 4, 5, 6]
#   smart_quotes      : lsquo,rsquo,ldquo,rdquo
#   input             : GFM
#   hard_wrap         : false
#   footnote_nr       : 1
#   show_warnings     : false