name = "xiyo-blog"
main = ".svelte-kit/output/server/index.js"
compatibility_date = "2024-12-01"

[assets]
directory = "./.svelte-kit/output/client"
binding = "ASSETS"

[env.production]
name = "xiyo-blog"
